module.exports.descriptors = [
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond',
    'Golden',
    'Whispering',
    'Enchanted',
    'Majestic',
    'Mossy',
    'Wild',
    'Serenity',
    'Mystical',
    'Emerald',
    'Hidden',
    'Glistening',
    'Sunset'
]

module.exports.places = [
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow',
    'Ridge',
    'Meadow',
    'Valley',
    'Summit',
    'Lake',
    'Trail',
    'Peak',
    'Island',
    'Beach',
    'Grove'
]